-- =============================================
-- CREATE TABLES SCRIPT
-- Thu tu: TAO BANG TRUOC, ADD FOREIGN KEY SAU
-- =============================================

-- BUOC 1: TAO TAT CA CAC BANG KHONG CO FOREIGN KEY HOAC CHI CO FK DON GIAN

-- 1. Bang ACCOUNTS (Khong co FK)
CREATE TABLE Accounts (
    AccountId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) NOT NULL UNIQUE,
    Password VARCHAR2(100) NOT NULL,
    Role NVARCHAR2(20) NOT NULL
);

-- 2. Bang CUSTOMERS (Co FK toi Accounts)
CREATE TABLE Customers (
    CustomerId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName NVARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    Address NVARCHAR2(200),
    Telephone VARCHAR2(20),
    DateOfBirth DATE,
    IdentityNum VARCHAR2(20),
    AccountId NUMBER,
    CONSTRAINT FK_Customer_Account FOREIGN KEY (AccountId) REFERENCES Accounts(AccountId)
);

-- 3. Bang EMPLOYEES (Co FK toi Accounts)
CREATE TABLE Employees (
    EmployeeId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName NVARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    PhoneNum VARCHAR2(20),
    Department NVARCHAR2(100),
    Position NVARCHAR2(100),
    AccountId NUMBER,
    CONSTRAINT FK_Employee_Account FOREIGN KEY (AccountId) REFERENCES Accounts(AccountId)
);

-- 4. Bang TOURS (Co FK toi Employees)
CREATE TABLE Tours (
    TourId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TourName NVARCHAR2(200) NOT NULL,
    TourType NVARCHAR2(50),
    BasePrice NUMBER(18, 2),
    Duration NVARCHAR2(50), 
    Description CLOB,
    ManagerId NUMBER, 
    CONSTRAINT FK_Tour_Manager FOREIGN KEY (ManagerId) REFERENCES Employees(EmployeeId)
);

-- 5. Bang TOUR_SCHEDULES (Co FK toi Tours)
CREATE TABLE TourSchedules (
    ScheduleId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TourId NUMBER NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    MaxCapacity NUMBER(5),
    CurrentBook NUMBER(5) DEFAULT 0,
    Status NVARCHAR2(50),
    CONSTRAINT FK_Schedule_Tour FOREIGN KEY (TourId) REFERENCES Tours(TourId)
);

-- 6. Bang BOOKINGS (Co FK toi Customers va TourSchedules)
CREATE TABLE Bookings (
    BookingId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerId NUMBER NOT NULL,
    ScheduleId NUMBER NOT NULL,
    BookingDate DATE DEFAULT SYSDATE,
    NumAdults NUMBER(3),
    NumChildren NUMBER(3),
    TotalAmount NUMBER(18, 2),
    Status NVARCHAR2(50),
    CONSTRAINT FK_Booking_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
    CONSTRAINT FK_Booking_Schedule FOREIGN KEY (ScheduleId) REFERENCES TourSchedules(ScheduleId)
);

-- 7. Bang BILLS (Co FK toi Bookings)
CREATE TABLE Bills (
    BillId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingId NUMBER NOT NULL,
    TotalCost NUMBER(18, 2),
    PaymentMethod NVARCHAR2(50),
    PaymentDate DATE DEFAULT SYSDATE,
    Status NVARCHAR2(50),
    CONSTRAINT FK_Bill_Booking FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId)
);

-- 8. Bang LOCATIONS (Khong co FK)
CREATE TABLE Locations (
    LocationId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LocationName NVARCHAR2(200) NOT NULL,
    Address NVARCHAR2(255),
    Description CLOB,
    LocationType NVARCHAR2(100)
);

-- 9. Bang SERVICES (Khong co FK)
CREATE TABLE Services (
    ServiceId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceType NVARCHAR2(100),
    ServiceName NVARCHAR2(200),
    Price NUMBER(18, 2)
);

-- 10. Bang TRANSPORTS (Khong co FK)
CREATE TABLE Transports (
    TransportId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LicensePlate VARCHAR2(20),
    VehicleType NVARCHAR2(50),
    ProviderName NVARCHAR2(100),
    DriverName NVARCHAR2(100),
    DriverPhoneNum VARCHAR2(20)
);

-- 11. Bang ACCOMMODATIONS (Khong co FK)
CREATE TABLE Accommodations (
    AccommodationId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type NVARCHAR2(50),
    Name NVARCHAR2(150),
    Address NVARCHAR2(255),
    ContactPhone VARCHAR2(20)
);

-- 12. Bang ITINERARIES (Co FK toi Tours va Transports)
CREATE TABLE Itineraries (
    ItineraryId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TourId NUMBER NOT NULL,
    DayNum NUMBER(3),
    Description CLOB,
    TransportId NUMBER,
    CONSTRAINT FK_Itinerary_Tour FOREIGN KEY (TourId) REFERENCES Tours(TourId),
    CONSTRAINT FK_Itinerary_Transport FOREIGN KEY (TransportId) REFERENCES Transports(TransportId)
);

-- =============================================
-- BUOC 2: TAO CAC BANG TRUNG GIAN (JUNCTION TABLES)
-- =============================================

-- 13. Bang ITINERARY_LOCATIONS
CREATE TABLE Itinerary_Locations (
    ItineraryId NUMBER NOT NULL,
    LocationId NUMBER NOT NULL,
    PRIMARY KEY (ItineraryId, LocationId),
    CONSTRAINT FK_IL_Itinerary FOREIGN KEY (ItineraryId) REFERENCES Itineraries(ItineraryId),
    CONSTRAINT FK_IL_Location FOREIGN KEY (LocationId) REFERENCES Locations(LocationId)
);

-- 14. Bang ITINERARY_SERVICES
CREATE TABLE Itinerary_Services (
    ItineraryId NUMBER NOT NULL,
    ServiceId NUMBER NOT NULL,
    PRIMARY KEY (ItineraryId, ServiceId),
    CONSTRAINT FK_IS_Itinerary FOREIGN KEY (ItineraryId) REFERENCES Itineraries(ItineraryId),
    CONSTRAINT FK_IS_Service FOREIGN KEY (ServiceId) REFERENCES Services(ServiceId)
);

-- 15. Bang ITINERARY_ACCOMMODATIONS
CREATE TABLE Itinerary_Accommodations (
    ItineraryId NUMBER NOT NULL,
    AccommodationId NUMBER NOT NULL,
    PRIMARY KEY (ItineraryId, AccommodationId),
    CONSTRAINT FK_IA_Itinerary FOREIGN KEY (ItineraryId) REFERENCES Itineraries(ItineraryId),
    CONSTRAINT FK_IA_Accommodation FOREIGN KEY (AccommodationId) REFERENCES Accommodations(AccommodationId)
);

-- =============================================
-- BUOC 3: COMMIT VA KIEM TRA
-- =============================================
COMMIT;

-- Kiem tra tat ca cac bang da duoc tao
PROMPT
PROMPT ========================================
PROMPT KIEM TRA CAC BANG DA TAO
PROMPT ========================================
PROMPT
SELECT table_name FROM user_tables ORDER BY table_name;

-- Kiem tra so luong bang (nen la 15)
PROMPT
PROMPT ========================================
PROMPT TONG SO BANG (nen la 15)
PROMPT ========================================
PROMPT
SELECT COUNT(*) AS "Total Tables" FROM user_tables;