-- =============================================
-- FILE: Fix_Sequences.sql
-- MỤC ĐÍCH: Reset tất cả sequences sau khi insert dữ liệu mẫu
-- CHẠY FILE NÀY SAU KHI CHẠY Tour_Admin_Localpro.sql
-- =============================================

SET SERVEROUTPUT ON;

DECLARE
    v_max_id NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('RESETTING ALL SEQUENCES');
    DBMS_OUTPUT.PUT_LINE('========================================');
    
    -- Reset sequence cho Accounts
    SELECT NVL(MAX(AccountId), 0) INTO v_max_id FROM Accounts;
    EXECUTE IMMEDIATE 'ALTER TABLE Accounts MODIFY AccountId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Accounts: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Customers
    SELECT NVL(MAX(CustomerId), 0) INTO v_max_id FROM Customers;
    EXECUTE IMMEDIATE 'ALTER TABLE Customers MODIFY CustomerId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Customers: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Employees
    SELECT NVL(MAX(EmployeeId), 0) INTO v_max_id FROM Employees;
    EXECUTE IMMEDIATE 'ALTER TABLE Employees MODIFY EmployeeId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Employees: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Tours
    SELECT NVL(MAX(TourId), 0) INTO v_max_id FROM Tours;
    EXECUTE IMMEDIATE 'ALTER TABLE Tours MODIFY TourId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Tours: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho TourSchedules
    SELECT NVL(MAX(ScheduleId), 0) INTO v_max_id FROM TourSchedules;
    EXECUTE IMMEDIATE 'ALTER TABLE TourSchedules MODIFY ScheduleId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ TourSchedules: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Bookings
    SELECT NVL(MAX(BookingId), 0) INTO v_max_id FROM Bookings;
    EXECUTE IMMEDIATE 'ALTER TABLE Bookings MODIFY BookingId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Bookings: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Bills
    SELECT NVL(MAX(BillId), 0) INTO v_max_id FROM Bills;
    EXECUTE IMMEDIATE 'ALTER TABLE Bills MODIFY BillId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Bills: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Locations
    SELECT NVL(MAX(LocationId), 0) INTO v_max_id FROM Locations;
    EXECUTE IMMEDIATE 'ALTER TABLE Locations MODIFY LocationId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Locations: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Services
    SELECT NVL(MAX(ServiceId), 0) INTO v_max_id FROM Services;
    EXECUTE IMMEDIATE 'ALTER TABLE Services MODIFY ServiceId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Services: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Transports
    SELECT NVL(MAX(TransportId), 0) INTO v_max_id FROM Transports;
    EXECUTE IMMEDIATE 'ALTER TABLE Transports MODIFY TransportId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Transports: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Accommodations
    SELECT NVL(MAX(AccommodationId), 0) INTO v_max_id FROM Accommodations;
    EXECUTE IMMEDIATE 'ALTER TABLE Accommodations MODIFY AccommodationId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Accommodations: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    -- Reset sequence cho Itineraries
    SELECT NVL(MAX(ItineraryId), 0) INTO v_max_id FROM Itineraries;
    EXECUTE IMMEDIATE 'ALTER TABLE Itineraries MODIFY ItineraryId GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';
    DBMS_OUTPUT.PUT_LINE('✓ Itineraries: ' || v_max_id || ' → Next: ' || (v_max_id + 1));
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('✅ ALL SEQUENCES RESET SUCCESSFULLY!');
    DBMS_OUTPUT.PUT_LINE('========================================');
END;
/

-- Kiểm tra MaxId hiện tại của mỗi bảng
SELECT 'Accounts' AS TableName, MAX(AccountId) AS MaxId FROM Accounts
UNION ALL
SELECT 'Customers', MAX(CustomerId) FROM Customers
UNION ALL
SELECT 'Employees', MAX(EmployeeId) FROM Employees
UNION ALL
SELECT 'Tours', MAX(TourId) FROM Tours
UNION ALL
SELECT 'TourSchedules', MAX(ScheduleId) FROM TourSchedules
UNION ALL
SELECT 'Bookings', MAX(BookingId) FROM Bookings
UNION ALL
SELECT 'Bills', MAX(BillId) FROM Bills
UNION ALL
SELECT 'Locations', MAX(LocationId) FROM Locations
UNION ALL
SELECT 'Services', MAX(ServiceId) FROM Services
UNION ALL
SELECT 'Transports', MAX(TransportId) FROM Transports
UNION ALL
SELECT 'Accommodations', MAX(AccommodationId) FROM Accommodations
UNION ALL
SELECT 'Itineraries', MAX(ItineraryId) FROM Itineraries
ORDER BY TableName;

SELECT * FROM CUSTOMERS